- name: "Alexandra von Bartschikowski"
  tasks:
    - "Pilates für Einsteiger"

- name: "Corinna Hanner-Schurr"
  tasks:
    - "Pilates"

- name: "Sabine Hrabowski"
  tasks:
    - "Linedance"

- name: "Christa Kiss"
  tasks:
    - "Faszien-Yoga"
    - "Fit auf dem Stuhl"
    - "Qigong"

- name: "Hanni und Herbert Maier"
  tasks:
    - "Wanderungen"

- name: "Karin Scherer"
  tasks:
    - "Aquafitness - Power & Fun"

- name: "Claudia Schmid"
  tasks:
    - "Aquafitness - Power & Fun"
    - "Bunte Gute-Laune-Stunde
"

- name: "Frank Schneider"
  tasks:
    - "Männer - Fit von Kopf bis Fuß"

- name: "Doris Seidl"
  tasks:
    - "Hatha-Yoga"

- name: "Anni Seiler"
  tasks:
    - "Wirbelsäulengymnastik"

- name: "Uschi Seyler"
  tasks:
    - "Aquafitness"

- name: "Susanne Thieme"
  tasks:
    - "Osteoporose-Gymnastik"
    - "Yoga - ganz entspannt"
    - "Hatha-Yoga"

- name: "Elisabeth Walter"
  tasks:
    - "Beckenboden-Gesundheitstraining"
    - "Bodystyling - Wand-workout"
    - "Rückenfitness - Wirbelsäulengymnastik"

- name: "Angelika Woller"
  tasks:
    - "Aquafitness"

